export const one = [
  { title: "1 Introduction.", link: "https://youtu.be/P9vM_Fw5fIs", practiclink: "" },
  { title: "2 Variables (переменные)", link: "https://youtu.be/h2z_id18FVQ", practiclink: "" },
  { title: "3 Math Operations", link: "https://youtu.be/vyPfRlW8dyQ", practiclink: "" },
  { title: "4   Math Operations 2", link: "https://youtu.be/lFJC3PcNCls", practiclink: "" },
  { title: "5   Conditional Statements", link: "https://youtu.be/Nzr-15-Pyb8", practiclink: "" },
  { title: "6   Loops (for)", link: "https://youtu.be/rSLrk5aqQeI", practiclink: "" },
  { title: "7   Loop in Java", link: "https://youtu.be/ndgvw5tsNFE", practiclink: "" },
  { title: "8   Array( Массив)", link: "https://youtu.be/BcWh1HMgUT0", practiclink: "" },
  { title: "9   Method void", link: "https://youtu.be/gWR0Ocs4nHI", practiclink: "" },
  { title: "10   Method return", link: "https://youtu.be/WiqKlniTRx4", practiclink: "" },
  { title: "11   Varargs, Foreach, String methods,GitHub", link: "https://youtu.be/iZm1mqpGRTY", practiclink: "" },
  { title: "12   OOP & Constructor", link: "https://youtu.be/eueeWTa3eF4", practiclink: "" },
  { title: "13   Encapsulation", link: "https://youtu.be/21T5kXKsKWs", practiclink: "" },
  { title: "14   Inheritance", link: "https://youtu.be/m93qIOo3S2Q", practiclink: "" },
  { title: "15   Modifiers", link: "https://youtu.be/UU_6g7Wqxkw", practiclink: "" },
  { title: "16   Polymorphism", link: "https://youtu.be/nQaCwu1RzJE", practiclink: "" },
  { title: "17   Abstraction- Abstract Class, Abstract Method", link: "https://youtu.be/YTLc5JbD2Vg", practiclink: "" },
  { title: "18   Abstraction-Interface", link: "https://youtu.be/f9OuEI0lPVw", practiclink: "" },
  { title: "19   Enum", link: "https://youtu.be/XYei7kHZl6E", practiclink: "" },
  { title: "20   Exception Handling", link: "https://youtu.be/_xQeEpHj_fQ", practiclink: "" },
  { title: "21   I/O Files, String, StringBuilder", link: "https://youtu.be/67Z6FYcP6B8", practiclink: "" },
  { title: "22   Extra session", link: "https://youtu.be/wVkgr09R52U", practiclink: "" },
  { title: "23   Project-OnlineShop", link: "https://youtu.be/vXh0Iky3fU0", practiclink: "" },
  { title: "24   Collection(ArrayList)", link: "https://youtu.be/QVf3_D0zi84", practiclink: "" },
  { title: "25   Collections(LinkedList)", link: "https://youtu.be/MlJGJVO9lxo", practiclink: "" },
  { title: "26   Set (HashSet, LinkedHashSet, TreeSet)", link: "https://youtu.be/7UOoABwR7sc", practiclink: "" },
  { title: "27   Map", link: "https://youtu.be/4ZYXRJcPJQc", practiclink: "" },
  { title: "28   Generic <T>", link: "https://youtu.be/jqaVU8VK7n4", practiclink: "" },
  { title: "29   Anonym Class, Lambda, Functional Interfcae", link: "https://youtu.be/CNsX6PU4RSg", practiclink: "" },
  { title: "30   MedCheck-Project", link: "https://lms.peaksoft.house/student/courses/118/materials/1819/task/1260/send-task", practiclink: "" },
  { title: "31   Stream-API", link: "https://youtu.be/SOzjk-S8Ifg", practiclink: "" },


];

export const two = [
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
  { title: "2222", link: " ", practiclink: "" },
];
export const three = [
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
  { title: "3333", link: " ", practiclink: "" },
];
export const four = [
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
  { title: "4444", link: " ", practiclink: "" },
];
